samples:
    ensemble: /data/cephfs/punim0010/projects/Saveliev_ICGC_MB/bcbio_300_50/final/2017-11-21_bcbio_decomposed/MB_300vs50-ensemble-annotated.vcf.gz
    vardict: /data/cephfs/punim0010/projects/Saveliev_ICGC_MB/bcbio_300_50/final/2017-11-21_bcbio_decomposed/MB_300vs50-vardict-annotated.vcf.gz
    mutect2: /data/cephfs/punim0010/projects/Saveliev_ICGC_MB/bcbio_300_50/final/2017-11-21_bcbio_decomposed/MB_300vs50-mutect2-annotated.vcf.gz
    varscan: /data/cephfs/punim0010/projects/Saveliev_ICGC_MB/bcbio_300_50/final/2017-11-21_bcbio_decomposed/MB_300vs50-varscan-annotated.vcf.gz
    normal_ensemble: /data/cephfs/punim0010/projects/Saveliev_ICGC_MB/bcbio_300_50/final/2017-11-21_bcbio_decomposed/MB_normal_50x-ensemble-annotated.vcf.gz

normals_dir: /home/vlad/validation/normals

hits_thresholds: [1, 2, 3]
