samples:
    ensemble: ../MB_300vs50-ensemble-annotated.vcf.gz
    vardict: ../MB_300vs50-vardict-annotated.vcf.gz
    mutect2: ../MB_300vs50-mutect2-annotated.vcf.gz
    strelka: ../MB_300vs50-strelka2-annotated.vcf.gz
    # normal_ensemble: ../MB_normal_50x-ensemble-annotated.vcf.gz

normals_dir: /data/cephfs/punim0010/projects/Saveliev_Somatic_validation/normals

hits_thresholds: [1, 2, 3]
